% -- Bootstrap resampling function library -- 
%    Enrique M. Quilis (October,2015)
% 
%        overlappingBB : Overlapping Block Bootstrap for a vector time series
%      overlappingBB_d : demo of overlappingBB()
% 
%         stationaryBB : Stationary Block Bootstrap for a vector time series
%       stationaryBB_d : demo of stationaryBB()
% 
%               seasBB : Seasonal Block Bootstrap for a vector time series
%             seasBB_d : demo of seasBB()
% 